[workspace]
members = ["lib/*", "wuwa-downloader", "wuwa-launcher"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
authors = ["Alvin Null <supdrewin@outlook.com>"]
repository = "https://github.com/supdrewin/wuwa-downloader/"

[workspace.dependencies]
wuwa-dl = { path = "lib/wuwa-dl" }
wuwa-macro-derive = { path = "lib/wuwa-macro-derive" }
